me: GreatestCommonDivisor_test
on: [push]

jobs:
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Permission Setting
      run: chmod +x GreatestCommonDivisor.sh Test.sh
    - name: Test Run
      run: ./Test.sh
